site_name: BiblioKeywords
site_url: https://example.com

nav:
    - Home: index.md
    - Utilities: utilities.md
    - Clean: clean.md
    - Config: config.md

theme:
    name: material
    analytics:
        gtag: G-11YWW45KYH


plugins: 
    - mkdocstrings

extra:
  analytics:
    provider: google
    property: G-11YWW45KYH