site_name: BiblioKeywords
site_url: https://example.com

nav:
    - Home: index.md
    - About: about.md
    - Utilities: utilities.md
    - Clean: clean.md

theme:
    name: material

plugins: 
    - mkdocstrings
