site_name: BiblioKeywords
site_url: https://example.com

nav:
    - Home: index.md
    - About: about.md
    - Utilities: utilities.md
    - Transform: transform.md

theme:
    name: material

plugins: 
    - mkdocstrings
